# Generated by Django 6.0.4 on 2026-04-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('PACK', 'Pack'), ('BOX', 'Box'), ('BAG', 'Bag'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('JAR', 'Jar'), ('G', 'Grams'), ('KG', 'Kilograms'), ('ML', 'Milliliters'), ('L', 'Liters'), ('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('CUP', 'Cup'), ('CUPS', 'Cups'), ('SLICE', 'Slice'), ('SLICES', 'Slices'), ('LEAVES', 'Leaves'), ('CLOVE', 'Clove'), ('CLOVES', 'Cloves'), ('PINCH', 'Pinch'), ('NONE', 'No unit')], default='NONE', max_length=10)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_entries', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
