# Generated by Django 6.0.4 on 2026-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('MEAT', 'Meat'), ('POULTRY', 'Poultry'), ('SEAFOOD', 'Seafood'), ('DAIRY', 'Dairy'), ('EGGS', 'Eggs'), ('BAKERY', 'Bakery'), ('GRAINS', 'Grains'), ('PASTA', 'Pasta'), ('RICE', 'Rice'), ('CANNED', 'Canned'), ('FROZEN', 'Frozen'), ('SNACKS', 'Snacks'), ('SWEETS', 'Sweets'), ('SPICES', 'Spices'), ('SEASONING', 'Seasoning'), ('OILS', 'Oils'), ('CONDIMENTS', 'Condiments'), ('SAUCES', 'Sauces'), ('BEVERAGES', 'Beverages'), ('TEA_COFFEE', 'Tea & Coffee'), ('NUTS_SEEDS', 'Nuts & Seeds'), ('LEGUMES', 'Legumes'), ('BREAKFAST', 'Breakfast'), ('BAKING', 'Baking'), ('BABY_FOOD', 'Baby Food'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('PACK', 'Pack'), ('BOX', 'Box'), ('BAG', 'Bag'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('JAR', 'Jar'), ('G', 'Grams'), ('KG', 'Kilograms'), ('ML', 'Milliliters'), ('L', 'Liters'), ('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('CUP', 'Cup'), ('CUPS', 'Cups'), ('SLICE', 'Slice'), ('SLICES', 'Slices'), ('LEAVES', 'Leaves'), ('CLOVE', 'Clove'), ('CLOVES', 'Cloves'), ('PINCH', 'Pinch'), ('NONE', 'No unit')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
