# Generated by Django 6.0.4 on 2026-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unit',
            new_name='default_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='allowed_units',
            field=models.JSONField(default=list, help_text='List of allowed unit values for this item'),
        ),
    ]
