# Generated by Django 6.0.4 on 2026-04-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_unit_item_default_unit_item_allowed_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_unit',
        ),
    ]
