# Generated by Django 6.0.4 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_servings_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('SALAD', 'Salad'), ('SOUP', 'Soup'), ('APPETIZER', 'Appetizer'), ('MAIN', 'Main Course'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
