# Generated by Django 6.0.4 on 2026-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_cuisines',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disliked_ingredients',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='DietaryPreference',
        ),
    ]
